name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action daily at midnight UTC
  workflow_dispatch:  # This allows you to manually trigger the action

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: AN-06  # Replace with your GitHub username
          outputs: |
            output/github-snake.svg
            output/github-snake-dark.svg?palette=github-dark
