name: Generate Snake Chart

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake Chart
        run: |
          npm install -g platane/snk  # Updated package name
          npx snk --github_user_name ${{ github.repository_owner }} --outputs dist/github-snake.svg
      
      - name: Upload Snake Chart
        uses: actions/upload-artifact@v3
        with:
          name: snake-chart
          path: dist/github-snake.svg
